################################################################################
# Makefile for publishing html content
#

publish:
	- mkdir -p ../../docs/2024/State_AQC_Tables
	mv Rmd/html/*.html ../../docs/2024/State_AQC_Tables

