################################################################################
# Makefile for publishing html content
#

publish:
	- mkdir -p ../../docs/2024/state_AQC_Tables
	mv Rmd/*.html ../../docs/2024/state_AQC_Tables

