---
title: "Chelan-Douglas-Okanogan Monitoring Data"
output:
  html_document: 
    css: report_styles.css
---

Processed on `r paste(lubridate::now(),format(lubridate::now(), "%Z"))`.

----


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE)

suppressPackageStartupMessages({
  library(MazamaSpatialUtils)
  library(AirMonitor)
  library(AirMonitorPlots)
})

# Year will be passed in a as a paremter
###year = 2014

startdate <- sprintf("%d0701", year)
enddate <- sprintf("%d1101", year)
timezone <- "America/Los_Angeles"
```

```{r load_data}
# NOTE:  These paths are relative to the Rmd/ directory
airnow <- get(load(sprintf("../data/airnow_%d.rda", year)))
airsis <- get(load(sprintf("../data/airsis_%d.rda", year)))
wrcc <- get(load(sprintf("../data/wrcc_%d.rda", year)))

# NOTE:  We put airnow last so it's meta and data will be used  if an ID appears more than once
monitor <-
  monitor_combine(
    wrcc, airsis, airnow,
    replaceMeta = TRUE,
    overlapStrategy = "replace all"
  ) %>%
  monitor_dropEmpty() %>%
  monitor_trimDate()

```

# Air Quality Monitors in `r year`

The Chelan-Douglas-Okanogan area had `r nrow(monitor$meta)` monitor-deployments 
during the `r year` July - October wildfire season. This includes both regulatory 
monitors that are part of the EPA AQS system as well as "temporary" monitors 
deployed by state and federal agencies during wildfires.

Click on a dot in the map below to learn more about each monitor-deployment.

```{r airnow_map}
monitor %>%
  monitor_leaflet(
    extraVars = c(
      "deploymentType",
      "dataIngestSource",
      "AQSID"
    )
  )
```

## Hourly data

It is ueful to plot hourly measurements and do a simple "gut check" visual QC
before we start combining them into daily averages.

```{r airnow_timeseriesPlot}
monitor %>%
  monitor_timeseriesPlot(
    addAQI = TRUE
  )

monitorCount <- nrow(monitor$meta) * 1.5
```

## Daily averages

```{r airnow_dailyBarplot, fig.height = monitorCount}
gg <-
  ggplot_pm25Timeseries(
    monitor,
    startdate = startdate,
    enddate = enddate
  ) +
  ggtitle("Daily average PM2.5") +
  stat_dailyAQCategory(timezone = timezone) +
  facet_grid(rows = vars(locationName))

suppressWarnings({ print(gg) })

```

-----





