---
title: "Air Quality Category Tables"
output:
  html_document: 
    css: report_styles.css
---

Processed on `r paste(lubridate::now(),format(lubridate::now(), "%Z"))`.

----

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE)

suppressPackageStartupMessages({
  library(AirMonitor)
})

# stateCode, timezone and month will be passed in a as a parameters
if ( FALSE ) {
  stateCode <- "GA"
  month <- 4
}

# NOTE:  Here we load a small dataset just so we can obtain the best timezone
timezone <-
  airnow_loadLatest() %>%
  monitor_filter(deploymentType != "Temporary") %>%
  monitor_filter(stateCode == !!stateCode) %>%
  monitor_bestTimezone()

monthName <- 
  MazamaCoreUtils::parseDatetime(
    sprintf("2024%02d15", month), 
    timezone = timezone
  ) %>% 
  strftime("%B", tzone = timezone)

stateName <-
  MazamaSpatialUtils::US_stateCodeToName(stateCode)

```

_Disclaimer: Data presented here come from a variety of sources and do not 
represent official EPA measurements. Please visit
[AirNow](https://www.airnow.gov) for official measurements._

----

```{r state_name, results = "asis"}
cat(sprintf("\n\n# %s in %s\n", monthName, stateName))
```


The following tables summarize the cumulative number of days air quality monitors spent in 
each AQI category during the the month of `r monthName`. Tables include only
permanent monitors.

The 'Old' row is calculated using the 2023 PM~2.5~ NAAQS while the 'New' row is
calculated using the 2024 PM~2.5~ NAAQS.


```{r year_loop, results = "asis", fig.width = 10, fig.height = 3, fig.align = "left"}

for ( year in 2014:2023 ) {
  
  # Define the local time month
  startString <- sprintf("%d%02d01", year, month)
  startdate <- MazamaCoreUtils::parseDatetime(startString, timezone = timezone)
  enddate <- startdate + lubridate::ddays(40)
  lubridate::day(enddate) <- 1
  
  # ----- Assemble data --------------------------------------------------------
  
  # NOTE:  These paths are relative to the Rmd/ directory
  airnow <- get(load(sprintf("../data/airnow_%d.rda", year)))
  
  monitor <-
    airnow %>%
    monitor_filter(stateCode == !!stateCode) %>%
    # NOT:  monitor_dailyStatistic() requires a single timezone
    monitor_filter(timezone == !!timezone)
  
  cat(sprintf("\n\n## %s %d -- %d permanent monitors\n", monthName, year, nrow(monitor$meta)))
  
  # Continue only if there is data
  if ( !monitor_isEmpty(monitor) ) {
    
    monitor <-
      monitor %>%
      monitor_filter(deploymentType != "Temporary") %>%
      monitor_filterDate(startdate, enddate)
    
    # Continue only if there is data
    if ( !monitor_isEmpty(monitor) ) {
      
      result <- try({
        
      # ----- Create table with rownames for printing ------------------------------
      
      oldAQCSummary <-
        monitor %>%
        monitor_dailyStatistic(
          FUN = mean,
          na.rm = TRUE,
          minHours = 18,
          dayBoundary = c("LST")
        ) %>%
        monitor_dropEmpty() %>%
        monitor_toAQCTable(NAAQS = "PM2.5") %>%
        colSums()
      
      newAQCSummary <-
        monitor %>%
        monitor_dailyStatistic(
          FUN = mean,
          na.rm = TRUE,
          minHours = 18,
          dayBoundary = c("LST")
        ) %>%
        monitor_dropEmpty() %>%
        monitor_toAQCTable(NAAQS = "PM2.5_2024") %>%
        colSums()
      
      dailyAQCTable <- 
        dplyr::bind_rows(oldAQCSummary, newAQCSummary) %>%
        as.data.frame()
      
      rownames(dailyAQCTable) <- c("Old", "New")
      
      # ----- Print table ----------------------------------------------------------
      
      print(knitr::kable(
        dailyAQCTable,
        format = "html", table.attr = "style='width:95%; font-size:1.5rem; margin: 20px 60px 0px 15px; line-height:2em'"
      ))
      
      # ----- Create barplot -------------------------------------------------------
      
      # Reorder so that the horizontal barplot ends up with Old on top 
      df_barplot <-
        dplyr::bind_rows(newAQCSummary, oldAQCSummary) %>%
        as.data.frame()
      
      rownames(df_barplot) <- c("New", "Old")
      
      par(mar = c(1,3,3,1) + 0.1)
      
      barplot(
        as.matrix(t(df_barplot)),
        col = c(US_AQI$colors_EPA, "gray90"),
        horiz = TRUE,
        las = 1,
        ylim = c(0, 1.5),
        width = 0.5,
        axes = FALSE
      )
      
      par(mar = c(5,4,4,2) + 0.1)
      
      # title("Title goes here")
      
      legend(
        "top",
        legend = c(US_AQI$names_eng, "Missing"),
        fill = c(US_AQI$colors_EPA, "gray90"),
        horiz = TRUE,
        cex = 0.8,
        bty = 'n'
      )
        
      }, silent = TRUE)
      
      if ( "try-error" %in% class(result) ) {
        
        cat(sprintf("\n`Processing error:  Unable to calculate tables.`\n"))
 
      }
      
    }
    
  }
  
}
```


