################################################################################
# Makefile for publishing html content
#

publish:
	cp Rmd/*.html ../../docs/2024/Chelan-Douglas_Health_District
	cp Rmd/html/*.html ../../docs/2024/Chelan-Douglas_Health_District

