################################################################################
# Makefile for publishing html content
#

publish:
	mv Rmd/*.html ../../docs/2024/Chelan-Douglas_Health_District
	mv Rmd/html/*.html ../../docs/2024/Chelan-Douglas_Health_District

